### ISSUE TITLE
Invalid Stream

### ISSUE THREAD

**Issue by BossHogg97** [TaTo30/VuePDF#10]
Hi, I'm working with Vue3.
The pdf data comes from the server and before passing it to your component I convert it as a UInt8Array but I have this warning that it doesn't allow me to view it. Any suggestions?

```
Warning: Setting up fake worker.
util.js:425 Warning: Indexing all PDF objects
util.js:425 Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 239"
util.js:425 Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 239"
util.js:425 Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 239"
```

I also post the instruction for data encoding:
```
var buf = Buffer.from(prop.data, 'utf-8')
const { pdf } = usePDF({ data: buf }
```

Thanks in advance

**Comment by TaTo30** [comment]
According this [Issue](https://github.com/wojtekmaj/react-pdf/issues/325):

* Check if the PDF can be loaded in browser, adobe or another viewer
* If yes, try to set request to get 'blob' type response or try to pass data in another format as base64

**Comment by BossHogg97** [comment]
Thanks for the help
