### ISSUE TITLE
Error when reusing usePDF

### ISSUE THREAD

**Issue by justCodeLife** [TaTo30/VuePDF#13]
The usePDF function only works on page load and when I try to use usePDF function later it gives this error :

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')
    at initDoc (index.js:333:21)
    at index.js:346:9
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at job (runtime-core.esm-bundler.js:1812:17)
    at flushPreFlushCbs (runtime-core.esm-bundler.js:336:13)
    at updateComponentPreRender (runtime-core.esm-bundler.js:5789:9)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5702:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)

Any idea ?

**Comment by starter-dev** [comment]
Can you show the code?

**Comment by justCodeLife** [comment]
Here you are !!


<template>
  <button @click="openPDF">OPEN PDF</button>
  <VuePDF :pdf="url" :page="1"/>
</template>

<script setup>
import {usePDF, VuePDF} from '@tato30/vue-pdf'
import {onMounted, ref} from "vue";

const url = ref(usePDF("sample.pdf").pdf) // THIS WORKS

url.value = usePDF("sample.pdf").pdf // THIS GIVES ERROR

onMounted(() => {
  url.value = usePDF("sample.pdf").pdf // THIS GIVES ERROR
})

setTimeout(() => {
  url.value = usePDF("sample.pdf").pdf // THIS GIVES ERROR
}, 2000)

function openPDF() {
  url.value = usePDF("sample.pdf").pdf // THIS GIVES ERROR
}

</script>

**Comment by justCodeLife** [comment]
Here you are !

```vue
<template>
  <button @click="openPDF">OPEN PDF</button>
  <VuePDF :pdf="url" :page="1"/>
</template>

<script setup>
import {usePDF, VuePDF} from '@tato30/vue-pdf'
import {onMounted, ref} from "vue";

const url = ref(usePDF("sample.pdf").pdf) // THIS WORKS

url.value = usePDF("sample.pdf").pdf // THIS GIVES ERROR

onMounted(() => {
  url.value = usePDF("sample.pdf").pdf // THIS GIVES ERROR
})

setTimeout(() => {
  url.value = usePDF("sample.pdf").pdf // THIS GIVES ERROR
}, 2000)

function openPDF() {
  url.value = usePDF("sample.pdf").pdf // THIS GIVES ERROR
}

</script>

```

**Comment by DvijIt** [comment]
@justCodeLife, how is it going? Did you manage it?

**Comment by DvijIt** [comment]
@justCodeLife thx a lot, may be author of lib is able to fix it)

**Comment by TaTo30** [comment]
`pdf` property is already a vue ref, but it doesn't has any value in first instance because usePDF gets the values from a promise method of pdfjs library. 
If you want to reuse usePDF in order to reassign the pdf property you need to watch it for a valid value. You can use this aproach:

```js
const { pdf } = usePDF('sample.pdf')

function changePDF() {
  const { pdf: newPDF } = usePDF('anothersample.pdf')
  watch(newPDF , () => {
    pdf.value = newPDF.value
  })
}
```

Check the [documentation](https://tato30.github.io/VuePDF/) for more elaborated example
