### ISSUE TITLE
Add typing support?

### ISSUE THREAD

**Issue by DustinDust** [TaTo30/VuePDF#19]
As of now, there is no .d.ts files, so typescript project can't detect the module `@tato30/vue-pdf`

If there is typings for this  library, could you kindly link me it?

**Comment by TaTo30** [comment]
Please do it, i would appreciate 😅. Lately, I haven't had much time to work in this library, so, any PR to improve the library is welcome. @leo91000

**Comment by leo91000** [comment]
> Please do it, i would appreciate 😅. Lately, I haven't had much time to work in this library, so, any PR to improve the library is welcome. @leo91000

No problem, would you prefere that I add `.d.ts` type definition for javascript files,  or do you prefer that I migrate javascript file to typescript ?
