### ISSUE TITLE
Access or support the .destory function

### ISSUE THREAD

**Issue by RobertJGabriel** [TaTo30/VuePDF#21]
@TaTo30 amazing work, just an idea. It would great to check this one load. 

"Uncaught (in promise) Error: Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.
"

PDFJS.getDocument({ url: pdf_url }).promise
    .then((pdf_doc) => {

        if (this.pdf_doc) {
            this.pdf_doc.destroy();
        }
        this.pdf_doc = pdf_doc;
        this.total_pages = this.pdf_doc.numPages;
    })

**Comment by TaTo30** [comment]
Do you have a example in order to reproduce this error?

**Comment by TaTo30** [comment]
The canvas error shouldn't throw with the last version, since it create a new canvas for each render process
