### ISSUE TITLE
Hook Support to modify annotations during the loading phase

### ISSUE THREAD

**Issue by gokaybiz** [TaTo30/VuePDF#25]
For the project I am working on, I need to be able to modify the annotations during loading and then, get the edited version (completely) after the user has edited it.

**Comment by TaTo30** [comment]
That could be a interesting feature.

The annotations you want to modify are that ones obtained from [getAnnotations()](https://github.com/mozilla/pdf.js/blob/22d350cae6df4caa13f3781074f978ae47f4f956/src/display/api.js#L1362)?

**Comment by gokaybiz** [comment]
Yeah, but when i override them, and then re-render, it won't affect anything...
Also, it's not returns updated annotations when user modify something.
Thanks in advance.

**Comment by gokaybiz** [comment]
@TaTo30 
Also when the user changes the scale (zoom in/zoom out), the annotations filled by the user are also reset, which is related to the question I asked in the first message.

**Comment by TaTo30** [comment]
The changes are already in latest version.

There two new features:

`annotations-map` prop, this prop must be a function that recieve an annotation as parameter and return the modified annotation or null in order to discard it.

```js
function annotationMap(annotation) {
  if (annotation.id === 'ID')
    annotation.fieldValue = 'Modified value'
  return annotation
}
<VuePDF  annotation-layer :annotations-map="annotationMap" />
```
`getAnnotationStorage` method. this method returns the document's [annotation storage.](https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_storage.js)

Also the scale issue was fixed.

**Comment by gokaybiz** [comment]
With the latest update, on a 61 page pdf (about 50 pages have annotations), it takes about 21 seconds for the annotations to render. during this time the pdf pages are displayed without the annotation layer.
Any idea why this might be?

Thanks for your work, by the way.

**Comment by TaTo30** [comment]
The layers (text and annotations) are displayed until the page finishes rendering, with a large pdf, rendering gets lazy.

**Comment by gokaybiz** [comment]
Is it possible to render asynchronously?

**Comment by TaTo30** [comment]
I need test it first, it will really helpful if you can share that pdf with me.
