### ISSUE TITLE
Rotation state not persisting in VuePDF with QPDF on subsequent loads

### ISSUE THREAD

**Issue by JoseCadenas** [TaTo30/VuePDF#27]
Hello,

I encountered an issue with rotation while using VuePDF in my implementation. Here are the details:

My implementation involves document scanning, followed by viewing the scanned PDF using VuePDF.
I provide the user with the ability to cycle through the pages and rotate the PDF using VuePDF props.
To persist the rotation changes, I store the rotation state per page per PDF and commit the changes on save.
I use the QPDF "--rotate" command to apply the rotations and save them to the PDF file.
However, upon reloading the PDF, the newly rotated pages (saved into the file) do not retain their rotation in VuePDF.

I would like to know how I can check the actual rotation of the PDF.

Thank you,
Jose

**Comment by TaTo30** [comment]
Currently `rotation` prop is for set an absolute rotation and it overwrite the default page rotation, so if you have a 90° rotated page and set 0 to rotation prop, you will get at 0° rotated page not 90°, you can check this by getting the rendered viewport through `loaded` event.

**Comment by JoseCadenas** [comment]
I see... i removed the rotation prop all together and still get 0 degree rotation. See screenshot of acrobate showing the correct rotation but my application (Using VuePDF) in the incorrect rotation and the loaded Viewport data.
![Screenshot 2023-06-14 at 5 23 59 PM](https://github.com/TaTo30/VuePDF/assets/50152606/a3c12e0d-c071-4823-80e6-9c10b675ffa9)

**Comment by TaTo30** [comment]
That is not working as it should. Can you provide me a rotated pdf using that QPDF? also, what version are you using?

**Comment by JoseCadenas** [comment]
VuePDF v1.4.8

I certainly can send you the file, whats the best method? Email?

**Comment by TaTo30** [comment]
Email is ok, aldo.hernandez3012@gmail.com

**Comment by JoseCadenas** [comment]
Sent

**Comment by TaTo30** [comment]
Already fixed in the latest version

**Comment by JoseCadenas** [comment]
Updated to v1.5.1 and can confirm it works as expected now. Thank you very much!
