### ISSUE TITLE
The version of pdfjs-dist is too high, resulting in incompatibility of earlier browsers

### ISSUE THREAD

**Issue by zp342519261** [TaTo30/VuePDF#29]
![image](https://github.com/TaTo30/VuePDF/assets/45960308/5905e60a-1cc9-44b8-8f72-8d21fadf9c3b)

**Comment by TaTo30** [comment]
What browser (and version) are you using?

**Comment by zp342519261** [comment]
chrome  69.0.3497.81

**Comment by zp342519261** [comment]
> What browser (and version) are you using?

chrome 69.0.3497.81

**Comment by oooplz** [comment]
And on Safari also has error

**Comment by TaTo30** [comment]
I'm afraid i can't help you, some features depends on latest versions of pdfjs-dist so i can't rollback to earlier versions, sorry. The only way i can think of is configuring the project bundler to transpile pdfjs-dist with a tool like babel or esbuild.
