### ISSUE TITLE
Not work with vue3 + vite + ts

### ISSUE THREAD

**Issue by MatthewTt** [TaTo30/VuePDF#3]
```
SyntaxError: The requested module '/node_modules/.vite/deps/@tato30_vue-pdf.js?t=1665368172537&v=db7c062b' does not provide an export named 'PDFProxy' (at PdfPreview.vue:16:1)
```

**Comment by TaTo30** [comment]
The lastest version updated `PDFProxy` to `usePDF` following Vue 3 [name convention](https://vuejs.org/guide/reusability/composables.html#naming). check the documentation, is up to date.

Consider upgrade the package in your project.
