### ISSUE TITLE
API version does not match the Worker Version 

### ISSUE THREAD

**Issue by pabloimrik17** [TaTo30/VuePDF#30]
Hi,

seems like mozilla released a new version of pdfjs three days ago and now the package is not working

![image](https://github.com/TaTo30/VuePDF/assets/5611863/7dab1d66-e175-4062-8cb7-826910ea992c)

https://github.com/mozilla/pdf.js/releases

Could this be fixed?

Also came to my mind this situation, each time mozilla makes a new release, this library will be broken until updated? Because browsers make auto updates and the idea scares me. Point me on the right direction if im wrong about this.

Thank you

**Comment by TaTo30** [comment]
It looks like you have 3.8.162 version of pdfjs installed in your project and the latest version of this library was built with 3.7.107 that's why the mismatch version error.

I think this could be fixed by ensure you have installed the 3.7.107 version of pdfjs-dist in your project, but how did you this error? have you installed this library with 3.7.107 pdfjs-dist and then updated? or this is from new project?

**Comment by pabloimrik17** [comment]
Hi, 

your point is right, there is a miss match in the version of pdfjs-dist installed as a dependency of your package, but this is what is hapenning.

Hi, 

your point is right, there is a miss match in the version of pdfjs-dist installed as a dependency of your package, but this is what is happening.

I uninstalled your package and every of pdfjs disappear in my package-lock

I install again your package and this is happening:

![image](https://github.com/TaTo30/VuePDF/assets/5611863/819eb48e-4b75-493c-a667-3d8d61eab233)

![image](https://github.com/TaTo30/VuePDF/assets/5611863/210b4990-7049-4f06-8bee-351474a62763)

![image](https://github.com/TaTo30/VuePDF/assets/5611863/262d84a9-2d83-4e42-b1cc-725529438a3d)

![image](https://github.com/TaTo30/VuePDF/assets/5611863/130d0bca-318c-45c6-85fe-f00ed35417e2)

**Comment by TaTo30** [comment]
I've fixed pdfjs version to avoid npm install an upper version, try again with the latest version (1.5.2) of the library.

**Comment by pabloimrik17** [comment]
Working now, thanks for the quick fix :D
