### ISSUE TITLE
Importance of importing 'pdfjs-dist/web/pdf_viewer.css'

### ISSUE THREAD

**Issue by rxw1** [TaTo30/VuePDF#35]
Hello Sir,
it may be just me, but I guess it should be stated somewhere quite prominently that since commit [a2c662e ](https://github.com/TaTo30/VuePDF/commit/a2c662e9fe210e95cb0920954901c69764ea09f9) from July 10, 2023,

```ts
import 'pdfjs-dist/web/pdf_viewer.css';
```

is necessary if any of `text-layer` or `annotation-layer` are used; otherwise, the canvas and the layers won't overlay at all.  Or would it be

```ts
import '@tato30/vue-pdf/style.css'
```

? But I can't find that one anywhere except in the updated examples in `/docs`.

Best regards

**Comment by TaTo30** [comment]
That is explained in the [documentation](https://tato30.github.io/VuePDF/guide/introduction.html#working-with-layers) website and the css import could be from `'@tato30/vue-pdf/style.css'` or `'pdfjs-dist/web/pdf_viewer.css'` both should works; but you're right, that info should be stated in the README too.

**Comment by TaTo30** [comment]
``` 
that info should be stated in the README too.
```
README updated.
