### ISSUE TITLE
Feature: Lazy Loading Support for Larger Files.

### ISSUE THREAD

**Issue by gokaybiz** [TaTo30/VuePDF#42]
On low-end devices, trying to render a ~60 page pdf with lots of annotations provides a very useless experience.

When I looked at the official repo for pdfjs web, I saw that they use lazy loading to render only a certain range of pages and use a loader placeholder for the rest.

If we can implement this, it will be great and it will increase the usability on low-end devices.

- [ ] Lazy Loading

**Comment by gokaybiz** [comment]
Some links that may be helpful:
https://github.com/mozilla/pdf.js/blob/8ad0f08099065dc19a4f17c07a130ac64ce124e9/web/pdf_page_view.js#L1036
https://github.com/search?q=repo%3Amozilla%2Fpdf.js+path%3A%2F%5Eweb%5C%2F%2F++RenderingStates.RUNNING&type=code

**Comment by TaTo30** [comment]
Thank you for the suggestion, but i think this feature can't be implemented since this library was designed for displaying individual pages with generic features related to the pages themselves.
