### ISSUE TITLE
usePDF方法的url設定無效

### ISSUE THREAD

**Issue by alex9061380** [TaTo30/VuePDF#45]
const url:any = 'https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf';官方範例url有效
const url:any = 'https://www.yamaha-motor.com.tw/images/motor/CYGNUS_GRYPHUS/B8R-F8199-T1.pdf';非官方url無效
const { pdf }:any = usePDF({ url });
用dir打印出的pdf.value是undefined

**Comment by TaTo30** [comment]
The `pdf` is a promised value, so you must wait for a resolved `pdf` if you want to access it, try this workaround using vue `watch`:

```js
const { pdf } = usePDF({url})
  watch(pdf , () => {
    console.log(pdf.value)
    // do something...
  })
```
