### ISSUE TITLE
Cannot destructure property 'style' of 'div' as it is null.

### ISSUE THREAD

**Issue by borankux** [TaTo30/VuePDF#49]
```bash
Uncaught (in promise) TypeError: Cannot destructure property 'style' of 'div' as it is null.
    at setLayerDimensions (util.js:17:1)
    at AnnotationLayer.render (util.js:17:1)
    at h (index.mjs:234:1)
```
I didn't even use the annotation-layer. I setit to `false`, yet this keeps happening. 

her is my code:
```vue
  <VuePDF v-for="(page) in totalPages"
              :key="page"
              :scale="1.3"
              :page="page"
              :annotation-layer="false"
              class="bg-orange-300 mb-[10px] w-full"
              :url="url"
              :pdf="pdfContent"
              @loaded="onLoaded" />
```

and I think it's happening in some kind of loop, then causing memory leak, because this what I see after opening the pdf for couple of times:
![img_v2_bff525da-9929-46a0-bb84-cc520d4a629g](https://github.com/TaTo30/VuePDF/assets/19632179/2067d2b5-e56c-4398-a2ce-e77ccb38e63c)

**Comment by TaTo30** [comment]
At a glance your code doesn't looks that has problems, if it's possible provide a complete example otherwise i wouldn't be able to help you much.

About memory leak, ensure closing the pdf using `destroy` function when you don't need it anymore, try this:

```js
const { pdf } = usePDF(pdfSample)

function destroyPdf(){
  pdf.value?.destroy()
}
```

**Comment by borankux** [comment]
> At a glance your code doesn't looks that has problems, if it's possible provide a complete example otherwise i wouldn't be able to help you much.
> 
> About memory leak, ensure closing the pdf using `destroy` function when you don't need it anymore, try this:
> 
> ```js
> const { pdf } = usePDF(pdfSample)
> 
> function destroyPdf(){
>   pdf.value?.destroy()
> }
> ```

I did destroy it but somehow even the loaded event is triggered, pdf is still rendering on the page. and when the component is unmounted, the rendering is still happening, it can't find the div. 

for example, on your demo page, https://tato30.github.io/VuePDF/examples/basic/all_pages.html , if I switch between routes too fast, I can re create this issue.

**Comment by TaTo30** [comment]
> i was hoping if there is a way to let the component stop everything when it's unmounted, not keep rendering in the background. since the element it self coult be undefined.

In that case use the `cancel` method: https://tato30.github.io/VuePDF/guide/methods.html#cancel

**Comment by borankux** [comment]
> > i was hoping if there is a way to let the component stop everything when it's unmounted, not keep rendering in the background. since the element it self coult be undefined.
> 
> In that case use the `cancel` method in `beforeUnmount` hook. https://tato30.github.io/VuePDF/guide/methods.html#cancel

thank you so much for your patientce, but canceling casused another problem:
![image](https://github.com/TaTo30/VuePDF/assets/19632179/77316a0a-0b69-43a5-8bd0-748cfa4c4610)

and there was warnings before it :
```bash
Warning: getTextContent - ignoring errors during "GetTextContent: page 31" task: "Error: Worker task was terminated".
```
and here is my code 

```vue
<script setup>
import {defineProps, onBeforeUnmount, onMounted, onUnmounted, ref, watch} from 'vue'
import {usePDF, VuePDF} from "@tato30/vue-pdf";
const props = defineProps({
  url: String,
})

let pdfContent = ref()
let totalPages = ref()
const showLoading = ref(true)
const loadingMessage = ref('Loading the document...')
const pdfRefs = ref([])
const floatToPercent = (num) => {
  return Math.round(num * 10000) / 100 + '%'
}

watch(() => props.url, (newVal) => {
  if(newVal) {
    const {pdf, pages} = usePDF(newVal, {
      onError: (error) => {
        loadingMessage.value = 'Loading failed. Please refresh the page.'
        pdf.value?.destroy().then(() => {
          console.log(error);
          pdfContent.value = null
        })
      },
      onProgress: (progress) => {
        loadingMessage.value = `Loaded...${floatToPercent(progress.loaded / progress.total)}`
      }
    })
    pdfContent = pdf
    totalPages = pages
  }
})

const handleLoaded = () => {
  showLoading.value = false
}

onBeforeUnmount(() => {
  try {
    pdfRefs.value.forEach((pdf) => {
      pdf?.cancel()
    })
    pdfContent.value?.destroy()
  } catch (e) {
    console.log('unable to cancel and destroy');
  }
})

</script>

<template>
  <div class="w-full h-full relative">
    <transition name="fade" mode="out-in">
      <div v-if="showLoading" class="absolute w-full h-full bg-white left-0 to-0 flex items-center justify-center">
        <div>
          {{loadingMessage}}
        </div>
      </div>
    </transition>
    <div class="w-full flex flex-col items-center justify-center">
      <VuePDF
          :page="page"
          :scale="1.5"
          :pdf="pdfContent"
          ref="pdfRefs"
          @loaded="handleLoaded"/>
    </div>
  </div>
</template>

<style>
.fade-enter-active, .fade-leave-active {
  transition: opacity .5s;
}
.fade-enter, .fade-leave-to {
  opacity: 0;
}
</style>
```

**Comment by borankux** [comment]
after testing, I found it only happens when using v-for to render all the pages. but in practice, I think rendering only one page has much better performance. Thank you for your support.
