### ISSUE TITLE
Load PDF from API

### ISSUE THREAD

**Issue by 1Map** [TaTo30/VuePDF#50]
I have a rest API which fetches the PDF through a url with JWT authentication.  How can the PDF be loaded with your component (Will appreciate an example) ?

Currently I call my rest API like:

```
            axios.get(API_URL + 'getpdf', {
                params,
                headers: { Authorization: `Bearer ${user.accessToken}` },
            }).then((response) => {
                return response;
            });
```

**Comment by TaTo30** [comment]
You can do it by using the pdf bytes:
```js
const { pdf } = usePDF({
    data: pdfBytes /*pdfBytes can be UInt8Array, Buffer or string bytes"*/
})

const { pdf } = usePDF(pdfBytes /*pdfBytes can be UInt8Array or Buffer*/)
```

Check this link for more details: https://github.com/mozilla/pdf.js/blob/67e1c37e0fea06951ece8c457c2b39d2ee2a683f/src/display/api.js#L133
