### ISSUE TITLE
Accessing the underlying canvas

### ISSUE THREAD

**Issue by MM-coder** [TaTo30/VuePDF#52]
How can I access the canvas generated by the `VuePDF` component, I'm looking to apply an SVG filter to the canvas component itself.

**Comment by borankux** [comment]
why not just do it on top of the div ?

**Comment by TaTo30** [comment]
I only can think of using `document.getElementsByTagName()`, but let me know if you need a specific solution.

**Comment by MM-coder** [comment]
@TaTo30 This fixed it perfectly, thank you :)
