### ISSUE TITLE
version 1.7.4 is not showing pdf

### ISSUE THREAD

**Issue by myomyintaung1411** [TaTo30/VuePDF#57]
Warning: loadFont - translateFont failed: "UnknownErrorException: CMapReaderFactory not initialized, see the `useWorkerFetch` parameter.".
util.js:380 Warning: Error during font loading: CMapReaderFactory not initialized, see the `useWorkerFetch` parameter.

my full code
<template>
    <section class="w-full h-screen relative">
          <VuePDF :pdf="pdf" text-layer annotation-layer />
    </section>
</template>

<script setup>
import pdfFile from '@/assets/yuanjing.pdf'
import { VuePDF, usePDF } from '@tato30/vue-pdf'
const { pdf, pages, info } = usePDF(pdfFile)
</script>

**Comment by TaTo30** [comment]
Try to disable useWorkerFetch parameter in usePDF

```js
const { pdf, pages, info } = usePDF({
  url: pdfFile,
  useWorkerFetch: false
})

```
