### ISSUE TITLE
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true.

### ISSUE THREAD

**Issue by Suniver** [TaTo30/VuePDF#61]
Hello, great component ! I gave you a star 👍 

All look great but when changing pages of the pdf with a button like in you example I get the following warning in the browser console:
`Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently`

Did not found anything related in the docs, is this a bad configuration on my side ? Or maybe some optimisation needed ?

**Comment by TaTo30** [comment]
Surely there is nothing bad with your setup, that is just a warning printed by the browser on how the canvas is used but according to this [issue](https://github.com/mozilla/pdf.js/issues/15662) isn't a big deal.
