### ISSUE TITLE
Change PDF dynamically and rerender

### ISSUE THREAD

**Issue by shanke-pvex** [TaTo30/VuePDF#62]
Is it possible to change the pdf source after init?
Here: const { pdf } = usePDF('sample.pdf') the file is fixed.
I want to show different pdf-files in a modal. Therefore i need to change the src and rerender the viewer.

Is it possible?

**Comment by TaTo30** [comment]
There is a way to do it, the example is here: https://tato30.github.io/VuePDF/examples/advanced/multiple_pdf.html

But isn't as reactivity as a vue component should be, i'll look forward to improve this use case. Meanwhile you can workaround as the above example.
