### ISSUE TITLE
Unexpected Token Module Parse Error

### ISSUE THREAD

**Issue by choff5507** [TaTo30/VuePDF#7]
I was looking forward to trying this library and I got the following error and I have no idea why. 

> Module parse failed: Unexpected token (315:41)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |     const clearLayers = () => {
> |       // Clear all childnodes of layer elements
> >       TextlayerREF.value.replaceChildren?.();
> |       AnnotationlayerRef.value.replaceChildren?.();
> |       // Clear event listeners of annotation layer

**Comment by mrpelancong** [comment]
same here

**Comment by TaTo30** [comment]
Your webpack loader seems can't parse optional chaining code, ensure you are using webpack 4 and babel 7 (or upper)

**Comment by flymorn** [comment]
same error:

Module parse failed: Unexpected token (315:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to
process this file. See https://webpack.js.org/concepts#loaders
|     const clearLayers = () => {
|       // Clear all childnodes of layer elements
>       TextlayerREF.value.replaceChildren?.();
|       AnnotationlayerRef.value.replaceChildren?.();
|       // Clear event listeners of annotation layer


using webpack 4 and babel 7,  check please.

**Comment by zavg** [comment]
Same here
