### ISSUE TITLE
New version release with highlighting feature

### ISSUE THREAD

**Issue by simonefranconetti97** [TaTo30/VuePDF#72]
@TaTo30 Is it possible to release a new version with the text highlighting feature? In the 1.8.1 version on NPM i can't see the `highlightText` and `highlightOptions` props, I think it's not aligned to the current master branch.

Thanks for your amazing work creating such a useful library

**Comment by TaTo30** [comment]
Version 1.9.0 has been released with the highlighting feature and other changes, check the releases page.
