### ISSUE TITLE
All PDFs not loaded

### ISSUE THREAD

**Issue by ahmedmaghraby** [TaTo30/VuePDF#75]
All PDFs in my project as well as examples in the library's documentation are failing to load.
![image](https://github.com/TaTo30/VuePDF/assets/38741761/a56ff19c-f5ab-4cc1-b617-de992894d36a)

**Comment by TaTo30** [comment]
PDFs are loading well in documentation website. Maybe your browser are blocking the worker, there are an error in console?

![imagen](https://github.com/TaTo30/VuePDF/assets/57086025/5badb260-2f60-4d73-82a7-4c570f690662)

**Comment by safi-okz** [comment]
PDF files are not load correctly

**Comment by ahmedmaghraby** [comment]
> PDFs are loading well in documentation website. Maybe your browser are blocking the worker, there are an error in console?
> 
> ![imagen](https://private-user-images.githubusercontent.com/57086025/291763213-5badb260-2f60-4d73-82a7-4c570f690662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjgyOTYsIm5iZiI6MTcwMzE2Nzk5NiwicGF0aCI6Ii81NzA4NjAyNS8yOTE3NjMyMTMtNWJhZGIyNjAtMmY2MC00ZDczLTgyYTctNGM1NzBmNjkwNjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE0MTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjkwZThiNDJhMWYyNTM2MjBmNDYyNDIwMzQ3NmY0MTM3OTRlMzk1ZjY5MzlkMDFiNDdiMmUxZGM3YzI3OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XCRWP9-Z4c6CUniLdBRlQS6IGfgO-Mp4qvT0W5iMoYE)

The service was down for approximately 5-6 hours. I am not sure what caused the issue. I have been using the library for the past 5 months and everything was functioning normally. However, suddenly, without any changes, all PDFs failed to load. After 5 hours, the service started working again, but I am still unsure about what happened.

**Comment by ahmedmaghraby** [comment]
> PDF files are not load correctly

what's your problem, safi?

**Comment by safi-okz** [comment]
I am getting the pdf through props and get this error
"chunk-ZQF6ASK3.js?v=e11c9d5e:2469 Uncaught (in promise) TypeError: Cannot
read properties of null (reading 'emitsOptions')
at shouldUpdateComponent"

**Comment by TaTo30** [comment]
> Did you depend on any online serves?

No, it didn't, actually the component works offline as well. Are you loading PDFs by URL? maybe the source was getting lost

**Comment by TaTo30** [comment]
> "chunk-ZQF6ASK3.js?v=e11c9d5e:2469 Uncaught (in promise) TypeError: Cannot
> read properties of null (reading 'emitsOptions')
> at shouldUpdateComponent"

It doesn't seem an VuePDF issue. Could you share the code?

**Comment by ahmedmaghraby** [comment]
> > Did you depend on any online serves?
> 
> No, it didn't, actually the component works offline as well. Are you loading PDFs by URL? maybe the source was getting lost

yes I'm using URL but the same URL working know anyway it's worked now I hope don't face this problem again
