### ISSUE TITLE
How to load a buffer containing a pdf ?

### ISSUE THREAD

**Issue by clabnet** [TaTo30/VuePDF#8]
I have a buffer loaded from server, can I open it with this code ? If yes, how to please ?

Thanks for this project, it work fine.

**Comment by TaTo30** [comment]
You can, by sending [DocumentInitParameters](https://github.com/mozilla/pdf.js/blob/67e1c37e0fea06951ece8c457c2b39d2ee2a683f/src/display/api.js#L133) object or just sending the data in the src param.

Examples:

```javascript
const { pdf } = usePDF({
    data: pdfBytes /*pdfBytes can be UInt8Array, Buffer or string bytes"*/
})

const { pdf } = usePDF(pdfBytes /*pdfBytes can be UInt8Array or Buffer*/)
```

**Comment by clabnet** [comment]
Run fine, thanks

**Comment by YipingRuan** [comment]
@TaTo30 
Should I use this feature to hold an empty PDF before the `onMounted` can decide the actual url of PDF?

**Comment by TaTo30** [comment]
I think you could do it and there are an example that could be helpful: [https://tato30.github.io/VuePDF/examples/advanced/multiple_pdf.html](https://tato30.github.io/VuePDF/examples/advanced/multiple_pdf.html).
But i'd rather just hide the component and show it when url has resolved.
