### ISSUE TITLE
 How can I use this library without upgrading my Vue version?

### ISSUE THREAD

**Issue by xuedaobian** [TaTo30/VuePDF#84]
I really like this library, and I feel that it meets all of my needs; but I am currently using Vue version 2.7.

**Comment by TaTo30** [comment]
Components developed in Vue 3 that use `setup` directive can't be used in Vue 2. Besides, Vue 2 is already deprecated by Vue team: https://vuejs.org/about/faq#is-vue-2-still-supported

> Vue 2.7, which was shipped in July 2022, is the final minor release of the Vue 2 version range. Vue 2 has now entered maintenance mode: it will no longer ship new features, but will continue to receive critical bug fixes and security updates for 18 months starting from the 2.7 release date. This means Vue 2 will reach End of Life on December 31st, 2023.


But if you _need_ to use Vue 2 you should take a look for this library that works on both Vue 2 and 3: https://github.com/hrynko/vue-pdf-embed.git

**Comment by zealot128** [comment]
FYI this library works without problems with Vue 2.7 unless you install it via npm/package.json.

We just copied the whole of `packages/vue-pdf/src/*` into our project and import it + use the same version of PDFjs-dist as this lib. With Vue 2.7 that works without issues. 

But using the version from NPM will not work, as it references some internal Vue functions that are not available in Vue 2.7
