### ISSUE TITLE
How to PDF fit to parent element's width?

### ISSUE THREAD

**Issue by zungssam** [TaTo30/VuePDF#9]
I want to set the width size of the PDF to 100%

**Comment by codingcronus** [comment]
Wrap your VuePDF component in a container:

`<div class="pdf-container">
  <VuePDF :pdf="pdf" :page="1" />
</div>`

Override the width and height properties using styling with a deep selector:

`.pdf-container span::v-deep canvas {
  width: 100% !important;
  height: auto !important;
}`

**Comment by TaTo30** [comment]
A new prop `"fit-parent"` has added for this feature.

Check the [README.md](https://github.com/TaTo30/VuePDF#fit-parent) to know how to use.
